### ISSUE TITLE
Returns many tracebacks when I start the thing

### ISSUE THREAD

**Issue by vides100** [LooveToLoose/DiscordSquidBot#2]
Here's the output when I try to start it:
```
2024-11-25 11:59:43 INFO     discord.client logging in using static token
Traceback (most recent call last):
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1025, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('162.159.137.232', 443)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/vidsc/SquiBot/main.py", line 79, in <module>
    bot.run(os.getenv("TOKEN"))
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/client.py", line 860, in run
    asyncio.run(runner())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/client.py", line 849, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/client.py", line 777, in start
    await self.login(token)
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/client.py", line 612, in login
    data = await self.http.static_login(token)
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/http.py", line 803, in static_login
    data = await self.request(Route('GET', '/users/@me'))
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/discord/http.py", line 625, in request
    async with self.__session.request(method, url, **kwargs) as response:
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/client.py", line 1197, in __aenter__
    self._resp = await self._coro
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/client.py", line 581, in _request
    conn = await self._connector.connect(
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 544, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 944, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1257, in _create_direct_connection
    raise last_exc
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1226, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/home/vidsc/SquiBot/venv/lib/python3.9/site-packages/aiohttp/connector.py", line 1033, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host discord.com:443 ssl:default [Connect call failed ('162.159.137.232', 443)]
```

**Comment by OmegaMetor** [comment]
This looks like a problem with your internet connection, such as something blocking access to discord?

**Comment by vides100** [comment]
Im at home and im happy to say it booted up
